### ISSUE TITLE
Tracking: Info-Beamer integration

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/freitagsfoo-web#3]
- [x] support checking if the Pi exists and is online
- [x] support getting the currently assigned setup
- [x] support assigning a setup
- [x] support sending commands (cfdecd395ccb045491ef3c1a16dd79ce2ae1895b)
