### ISSUE TITLE
Tracking: Wiki integration

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/freitagsfoo-web#4]
features:
- [x] support displaying a table of talks
  - [x] title
  - [x] persons
  - [ ] description (see https://github.com/chaosdorf/freitagsfoo-wiki-json/issues/1)
  - [x] link to wiki page
- [ ] support adding talks
- [ ] support modifying talks
- [ ] support removing talks
- [ ] support moving talks

means:
- [x] link to the correct wiki page
- [x] fetch `freitagsfoo.json`
- [ ] display wiki-markup to copy-paste
- [ ] modify the wiki page
