### ISSUE TITLE
Tracking: mpd integration

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/freitagsfoo-web#5]
- [ ] connect to mpd
- [ ] pause music when talks start and resume when talks finish
- [ ] nice fade-in and fade-out
- [ ] play background music in between talks

**Comment by YtvwlD** [comment]
mpd is not really being used anymore
