### ISSUE TITLE
Tracking: dorfmap integration

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/freitagsfoo-web#6]
- [ ] connection to dorfmap
- [ ] check if the speakers are on
- [ ] support turning speakers on
- [ ] check if the projector is on
- [ ] support turning the projector on
- [ ] support turning the projector off
- [ ] support switching the projector's input
